name: Test Demo
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  build:
    name: 'Test Demo'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Free up space
        run: |
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/share/dotnet
      - name: Install cuSPARSELt for pytorch
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cusparselt cusparselt-cuda-12
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25.0.0'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Build and run demo
        run: |
          ./gradlew -i bootRun &
          sbpid="$!"
          sleep 1200
          curl --silent --fail-with-body http://localhost:8080/hello
          curl --silent -L -o test.pdf https://raw.githubusercontent.com/microsoft/markitdown/e921497f794e8f6a6cdf9872d2a29e187448c7eb/packages/markitdown/tests/test_files/test.pdf
          curl --silent --fail-with-body http://localhost:8080/convert -F "file=@test.pdf"
          kill $sbpid
